### ISSUE TITLE
What wrong ? ERROR: EigenGeneral not defined

### ISSUE THREAD

**Issue by paulanalyst** [andreasnoack/LinearAlgebra.jl#1]
What wrong ? 
ERROR: EigenGeneral not defined 
error in last line. All packages are instled.

               _
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: http://docs.julialang.org
   _ _   _| |_  __ _   |  Type "help()" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.4.0-dev+1984 (2014-12-07 23:20 UTC)
 _/ |\__'_|_|_|\__'_|  |  Commit 052f54e (24 days old master)
|__/                   |  x86_64-w64-mingw32

julia> using LinearLeastSquares
ERROR: LinearLeastSquares not found
 in require at loading.jl:47

julia> A = big(randn(3,3));b = A*ones(3)
3-element Array{Base.MPFR.BigFloat,1}:
 -2.9446960791946807933783247790415771305561065673828125e-01
  3.236218918047749248945166300472919829189777374267578125e+00
 -2.56092452427787808932890811774996109306812286376953125e+00

julia> A\b # by LU
3-element Array{Base.MPFR.BigFloat,1}:
 1.000000000000000000000000000000000000000000000000000000000000000000000000000017e+00
 1.000000000000000000000000000000000000000000000000000000000000000000000000000017e+00
 9.999999999999999999999999999999999999999999999999999999999999999999999999999827e-01

julia> qrfact(A)\b
3-element Array{Base.MPFR.BigFloat,1}:
 1.000000000000000000000000000000000000000000000000000000000000000000000000000017e+00
 1.000000000000000000000000000000000000000000000000000000000000000000000000000035e+00
 9.999999999999999999999999999999999999999999999999999999999999999999999999999741e-01

julia> cholfact(A'A)\(A'b)
3-element Array{Base.MPFR.BigFloat,1}:
 1.000000000000000000000000000000000000000000000000000000000000000000000000000017e+00
 1.000000000000000000000000000000000000000000000000000000000000000000000000000017e+00
 1e+00

julia> vr, vi, v3 = big(randn(3)), big(randn(3)), big(randn(3));

julia> V = [vr + vi*im vr - vi*im  v3];

julia> V = [vr + vi*im vr - vi*im  v3]
3x3 Array{Complex{Base.MPFR.BigFloat},2}:
 -2.92480246431090773473471244869870133697986602783203125e-01-1.23301741773709269689440759520948631688952445983886
71875e-01im    -6.248288026283737028876430485979653894901275634765625e-01+0e+00im
     1.2486111443976664059363201886299066245555877685546875e+00-4.780390824486795975367670052946778014302253723144
53125e-01im     -1.437786704485576105838617877452634274959564208984375e+00+0e+00im
    4.5285454219578136214607866349979303777217864990234375e-02-7.6873228736745721767498196186352288350462913513183
59375e-02im     -8.374534723584889928105212675291113555431365966796875e-01+0e+00im

julia> A = real(V*diagm([1 + im, 1 - im, 1])/V)
3x3 Array{Base.MPFR.BigFloat,2}:
  2.576802034195741440834721530934809151596626451040076198981114681613706386162393e+00    -2.111621855823541931575
384837701543463270383359650712117854830826270375426030325e+00
 -8.559677601741757504896778861974182932186714773709164352191451088403852069777578e+00      9.78052219886619411959
11689523504923366255761234952124648193339633989847339366e+00
 -4.188140715194974510238856704548191419461734044485174519602972737487350197843463e-01      1.40012483629965998591
0674299516564706036794287389179472732815371667614610927464e+00

julia> LinearAlgebra.EigenGeneral.eigvals!(copy(A))
ERROR: LinearAlgebra not defined

julia> Pkg.clone("https://github.com/andreasnoack/LinearAlgebra.jl")
INFO: Cloning LinearAlgebra from https://github.com/andreasnoack/LinearAlgebra.jl
INFO: Computing changes...

julia> LinearAlgebra.EigenGeneral.eigvals!(copy(A))
ERROR: LinearAlgebra not defined

julia> A
3x3 Array{Base.MPFR.BigFloat,2}:
  2.576802034195741440834721530934809151596626451040076198981114681613706386162393e+00    -2.111621855823541931575
384837701543463270383359650712117854830826270375426030325e+00
 -8.559677601741757504896778861974182932186714773709164352191451088403852069777578e+00      9.78052219886619411959
11689523504923366255761234952124648193339633989847339366e+00
 -4.188140715194974510238856704548191419461734044485174519602972737487350197843463e-01      1.40012483629965998591
0674299516564706036794287389179472732815371667614610927464e+00

julia> using LinearAlgebra
ERROR: ArrayViews not found
 in require at loading.jl:47
 in include at boot.jl:242
 in include_from_node1 at loading.jl:128
 in include at boot.jl:242
 in include_from_node1 at loading.jl:128
 in reload_path at loading.jl:152
 in _require at loading.jl:67
 in require at loading.jl:51
while loading C:\Users\SAMSUNG2\.julia\v0.4\LinearAlgebra\src\cholesky.jl, in expression starting on line 6
while loading C:\Users\SAMSUNG2\.julia\v0.4\LinearAlgebra\src\LinearAlgebra.jl, in expression starting on line 11

julia> Pkg.update()
INFO: Updating METADATA...
INFO: Updating LinearAlgebra...
INFO: Computing changes...
INFO: No packages to install, update or remove

julia> Pkg.add("ArrayVievs")
ERROR: unknown package ArrayVievs
 in wait at task.jl:51
 in sync_end at task.jl:311
 in add at pkg/entry.jl:319
 in add at pkg/entry.jl:71
 in anonymous at pkg/dir.jl:28
 in cd at file.jl:30
 in cd at pkg/dir.jl:28
 in add at pkg.jl:20

julia> Pkg.add("ArrayViews")
INFO: Cloning cache of ArrayViews from git://github.com/JuliaLang/ArrayViews.jl.git
INFO: Installing ArrayViews v0.4.8
INFO: Package database updated

julia> Pkg.update()
INFO: Updating METADATA...
INFO: Updating LinearAlgebra...
INFO: Computing changes...
INFO: No packages to install, update or remove

julia> using LinearAlgebra

julia> A
3x3 Array{Base.MPFR.BigFloat,2}:
  2.576802034195741440834721530934809151596626451040076198981114681613706386162393e+00    -2.111621855823541931575
384837701543463270383359650712117854830826270375426030325e+00
 -8.559677601741757504896778861974182932186714773709164352191451088403852069777578e+00      9.78052219886619411959
11689523504923366255761234952124648193339633989847339366e+00
 -4.188140715194974510238856704548191419461734044485174519602972737487350197843463e-01      1.40012483629965998591
0674299516564706036794287389179472732815371667614610927464e+00

julia> LinearAlgebra.EigenGeneral.eigvals!(copy(A))
ERROR: EigenGeneral not defined

Paul

**Comment by andreasnoack** [comment]
Please to update the package and run
```julia
julia> using LinearAlgebra

julia> LinearAlgebra.EigenGeneral.eigvals!(big(randn(3,3)))
3-element Array{Complex{Base.MPFR.BigFloat},1}:
 1.033499471569389278898272403944768395642310326742203816603736140528081530377204e+00+0e+00im
 5.590179364779205625027761128833241108666432735803502055577979672737409286337721e-01-0e+00im
 2.268104923801678001260764857606039622444980115497758477838465892198177540989127e+00+0e+00im
```

**Comment by paulanalyst** [comment]
Unfortunatly still the same:
ERROR: EigenGeneral not defined
Paul               _
    _       _ _(_)_     |  A fresh approach to technical computing
   (_)     | (_) (_)    |  Documentation: http://docs.julialang.org
    _ _   _| |_  __ _   |  Type "help()" for help.
   | | | | | | |/ _` |  |
   | | |_| | | | (_| |  |  Version 0.3.3 (2014-11-23 20:19 UTC)
  _/ |\__'_|_|_|\__'_|  |  Official http://julialang.org/ release
|__/                   |  x86_64-w64-mingw32

julia> Pkg.update("LinearAlgebra")
ERROR: `update` has no method matching update(::ASCIIString)

julia> Pkg.update()
INFO: Updating METADATA...
INFO: Updating cache of MinimalPerfectHashes...
INFO: Updating cache of Grid...
INFO: Updating cache of HDF5...
INFO: Updating cache of MinimalPerfectHashes...
INFO: Updating FLANN...
INFO: Updating Distributions...
INFO: Computing changes...
INFO: Upgrading Grid: v0.3.6 => v0.3.7
INFO: Upgrading HDF5: v0.4.8 => v0.4.9
INFO: Building Blosc
INFO: Building LibCURL
INFO: Updating WinRPM package list
INFO: Downloading http://download.opensuse.org/repositories/windows:/mingw:/win32/openSUSE_13.1//repodata/repomd.x
ml
INFO: Downloading http://download.opensuse.org/repositories/windows:/mingw:/win32/openSUSE_13.1//repodata/681cecec
920b200d32ac3243fe1ffe26e3d8d4a56794449c6bee04a956cef51a-primary.xml.gz
INFO: Downloading http://download.opensuse.org/repositories/windows:/mingw:/win64/openSUSE_13.1//repodata/repomd.x
ml
INFO: Downloading http://download.opensuse.org/repositories/windows:/mingw:/win64/openSUSE_13.1//repodata/ff0286bb
9058c26f31af33aaf85e0478a4a4e6d84eedb333132f33c75be44d24-primary.xml.gz
INFO: Building WinRPM
INFO: Downloading http://download.opensuse.org/repositories/windows:/mingw:/win32/openSUSE_13.1//repodata/repomd.x
ml
INFO: Downloading http://download.opensuse.org/repositories/windows:/mingw:/win64/openSUSE_13.1//repodata/repomd.x
ml
INFO: Building HDF5

julia> using LinearAlgebra
ERROR: LinearAlgebra not found
  in require at loading.jl:47

julia> Pkg.add("LinearAlgebra")
ERROR: unknown package LinearAlgebra
  in wait at task.jl:51
  in add at pkg/entry.jl:319
  in add at pkg/entry.jl:44

julia> Pkg.clone("https://github.com/andreasnoack/LinearAlgebra.jl")
INFO: Cloning LinearAlgebra from https://github.com/andreasnoack/LinearAlgebra.jl
INFO: Computing changes...

julia> using LinearAlgebra
ERROR: too many parameters for type Symmetric
  in include at boot.jl:245
  in include_from_node1 at loading.jl:128
while loading C:\Users\SAMSUNG2\.julia\v0.3\LinearAlgebra\src\juliaBLAS.jl, in expression starting on line 29
while loading C:\Users\SAMSUNG2\.julia\v0.3\LinearAlgebra\src\LinearAlgebra.jl, in expression starting on line 3

julia> LinearAlgebra.EigenGeneral.eigvals!(big(randn(3,3)))
ERROR: EigenGeneral not defined

julia> Pkg.update()
INFO: Updating METADATA...
INFO: Updating cache of MinimalPerfectHashes...
INFO: Updating cache of MinimalPerfectHashes...
INFO: Updating FLANN...
INFO: Updating LinearAlgebra...
INFO: Updating Distributions...
INFO: Computing changes...
INFO: No packages to install, update or remove

julia> using LinearAlgebra

julia> LinearAlgebra.EigenGeneral.eigvals!(big(randn(3,3)))
ERROR: EigenGeneral not defined

julia>

Paul

W dniu 2015-01-04 o 17:20, Andreas Noack pisze:

**Comment by andreasnoack** [comment]
Could you try with latest master, i.e. 0.4?

**Comment by paulanalyst** [comment]
After Uninstall 0.4 and fresh install    :

    _       _ _(_)_     |  A fresh approach to technical computing
   (_)     | (_) (_)    |  Documentation: http://docs.julialang.org
    _ _   _| |_  __ _   |  Type "help()" for help.
   | | | | | | |/ _` |  |
   | | |_| | | | (_| |  |  Version 0.4.0-dev+2438 (2015-01-03 12:36 UTC)
  _/ |\__'_|_|_|\__'_|  |  Commit b0d94dd (1 day old master)
|__/                   |  x86_64-w64-mingw32

julia> Pkg.installed()
Dict{ASCIIString,VersionNumber} with 16 entries:
   "LibExpat"           => v"0.0.5"
   "FixedPointNumbers"  => v"0.0.6"
   "WinRPM"             => v"0.1.6"
   "SHA"                => v"0.0.3"
   "LinearAlgebra"      => v"0.0.0-"
   "IniFile"            => v"0.2.4"
   "Tk"                 => v"0.2.16"
   "Color"              => v"0.3.15"
   "ArrayViews"         => v"0.4.8"
   "LinearLeastSquares" => v"0.0.10"
   "Winston"            => v"0.11.7"
   "Compat"             => v"0.2.7"
   "Zlib"               => v"0.1.7"
   "BinDeps"            => v"0.3.7"
   "Cairo"              => v"0.2.21"
   "URIParser"          => v"0.0.3"

julia> using LinearAlgebra
ERROR: T not defined
  in include at boot.jl:248
  in include_from_node1 at loading.jl:128
  in include at boot.jl:248
  in include_from_node1 at loading.jl:128
  in reload_path at loading.jl:152
  in _require at loading.jl:67
  in require at loading.jl:51
while loading C:\Users\SAMSUNG2\.julia\v0.4\LinearAlgebra\src\qr.jl, in 
expression starting on line 10
while loading 
C:\Users\SAMSUNG2\.julia\v0.4\LinearAlgebra\src\LinearAlgebra.jl, in 
expression starting on line 13

julia> Pkg.update()
INFO: Updating METADATA...
INFO: Updating LinearAlgebra...
INFO: Computing changes...
INFO: No packages to install, update or remove

julia> using LinearAlgebra

julia> LinearAlgebra.EigenGeneral.eigvals!(big(randn(3,3)))
ERROR: EigenGeneral not defined

julia> Pkg.clone("https://github.com/andreasnoack/LinearAlgebra.jl")
INFO: Cloning LinearAlgebra from 
https://github.com/andreasnoack/LinearAlgebra.jl
ERROR: LinearAlgebra already exists
  in error at error.jl:21 (repeats 2 times)

julia>
Paul
W dniu 2015-01-05 o 13:22, Andreas Noack pisze:

**Comment by jiahao** [comment]
Looks like this is closed by be31ac6c254494287c79d1d186d488235a733a88

**Comment by paulanalyst** [comment]
Still error, what now ?

               _
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: http://docs.julialang.org
   _ _   _| |_  __ _   |  Type "help()" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.3.3 (2014-11-23 20:19 UTC)
 _/ |\__'_|_|_|\__'_|  |  Official http://julialang.org/ release
|__/                   |  x86_64-w64-mingw32

julia>  Pkg.update()
INFO: Updating METADATA...
INFO: Updating cache of MinimalPerfectHashes...
INFO: Updating cache of LibExpat...
INFO: Updating cache of Compat...
INFO: Updating cache of DataArrays...
INFO: Updating cache of MinimalPerfectHashes...
INFO: Updating FLANN...
INFO: Updating LinearAlgebra...
INFO: Updating Distributions...
INFO: Computing changes...
INFO: Upgrading Compat: v0.2.7 => v0.2.9
INFO: Upgrading DataArrays: v0.2.7 => v0.2.8
INFO: Upgrading LibExpat: v0.0.4 => v0.0.6

julia> using LinearAlgebra
ERROR: too many parameters for type Symmetric
 in include at boot.jl:245
 in include_from_node1 at loading.jl:128
while loading C:\Users\SAMSUNG2\.julia\v0.3\LinearAlgebra\src\juliaBLAS.jl, in expression starting on line 29
while loading C:\Users\SAMSUNG2\.julia\v0.3\LinearAlgebra\src\LinearAlgebra.jl, in expression starting on line 3

julia> Pkg.clone("https://github.com/andreasnoack/LinearAlgebra.jl")
INFO: Cloning LinearAlgebra from https://github.com/andreasnoack/LinearAlgebra.jl
ERROR: LinearAlgebra already exists
 in error at error.jl:21

julia>
Paul

**Comment by andreasnoack** [comment]
As I wrote earlier: try 0.4. This package is for development.

**Comment by paulanalyst** [comment]
Thx , Is ok like below.
Now I have eigvals. How to compute eigenvecetors? 
Somthing like this ? :
julia> LinearAlgebra.EigenGeneral.eigvecs!(big(R))
ERROR: eigvecs! not defined

julia> LinearAlgebra.EigenGeneral.eig!(big(R))
ERROR: eig! not defined

julia> LinearAlgebra.EigenGeneral.eig(big(R))
ERROR: `eigfact!` has no method matching eigfact!(::Array{Base.MPFR.BigFloat,2})
 in eigfact at linalg/factorization.jl:485


Paul






julia> using LinearAlgebra

julia> LinearAlgebra.EigenGeneral.eigvals!(big(randn(3,3)))
3-element Array{Complex{Base.MPFR.BigFloat},1}:
  1.534623321001092588097211891345701174971044871663075078702582149053365419085907e+00+0e+00im
 -1.186039361803352686036706742164480587491646873332092208102786810715894228511819e+00-0e+00im
  3.123010490893330149498578220872572621829059262295640044002046616625288094259811e-01+0e+00im

julia> D=readcsv("v4dane.txt")
2888x4 Array{Float64,2}:
julia> R=big(cor(D))
4x4 Array{Base.MPFR.BigFloat,2}:
  1e+00                                                                1.64140231452973156534014265162113588303327
5604248046875e-02
  8.478883454207176983974392214804538525640964508056640625e-02         -4.3457417702650385712970226848028687527403
23543548583984375e-03
 -1.8891061616368473412286288493078245664946734905242919921875e-03      2.3616527426152886248722495565743884071707
72552490234375e-01
  1.641402314529731565340142651621135883033275604248046875e-02          1e+00


julia> LinearAlgebra.EigenGeneral.eigvals!(big(R))
4-element Array{Complex{Base.MPFR.BigFloat},1}:
 9.136780960976265900170305404376001632503780825524462872623450285701651179914396e-01+0e+00im
 7.625883782303111997402638441007372493673195053161392576369678086568223851918953e-01-0e+00im
 1.085618526889408511865030283853044736864699856915245499071347266525737353830847e+00+0e+00im
 1.238114998782653698377675331608617850517602555216168956029339896247275142985749e+00+0e+00im

**Comment by andreasnoack** [comment]
For now, you'll have to use inverse iteration, i.e.
```julia
vals = eigvals(A)
vec = ones(size(A,1))
vec = (A - vals[end]*I)\vec
vec /= norm(vec)
vec = (A - vals[end]*I)\vec
vec /= norm(vec)
```
which should be enough iterations.
